spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news_demo?serverTimezone=UTC
    username: root
    password: '016016'

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml